# Generated by Django 5.0.3 on 2024-03-11 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_task_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["status", "-datetime"]},
        ),
    ]
